# Generated by Django 3.2 on 2021-05-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210509_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'verbose_name': 'Rating star', 'verbose_name_plural': 'Rating stars'},
        ),
    ]
